package com.contest.mapper;

import com.contest.model.KefuChatModel;
import com.contest.model.KefuChatModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KefuChatModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    long countByExample(KefuChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int deleteByExample(KefuChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int insert(KefuChatModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int insertSelective(KefuChatModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    List<KefuChatModel> selectByExample(KefuChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    KefuChatModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int updateByExampleSelective(@Param("record") KefuChatModel record, @Param("example") KefuChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int updateByExample(@Param("record") KefuChatModel record, @Param("example") KefuChatModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int updateByPrimaryKeySelective(KefuChatModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kefu_chat
     *
     * @mbg.generated Wed Apr 17 13:57:41 CST 2019
     */
    int updateByPrimaryKey(KefuChatModel record);
}