package com.contest.model;

import java.util.Date;

public class CodeHistModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_hist.id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_hist.submit_time
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    private Date submitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_hist.user_id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_hist.result
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_hist.problem_id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_code_hist.code
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    private String code;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_hist.id
     *
     * @return the value of t_code_hist.id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_hist.id
     *
     * @param id the value for t_code_hist.id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_hist.submit_time
     *
     * @return the value of t_code_hist.submit_time
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public Date getSubmitTime() {
        return submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_hist.submit_time
     *
     * @param submitTime the value for t_code_hist.submit_time
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public void setSubmitTime(Date submitTime) {
        this.submitTime = submitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_hist.user_id
     *
     * @return the value of t_code_hist.user_id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_hist.user_id
     *
     * @param userId the value for t_code_hist.user_id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_hist.result
     *
     * @return the value of t_code_hist.result
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_hist.result
     *
     * @param result the value for t_code_hist.result
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_hist.problem_id
     *
     * @return the value of t_code_hist.problem_id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_hist.problem_id
     *
     * @param problemId the value for t_code_hist.problem_id
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_code_hist.code
     *
     * @return the value of t_code_hist.code
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_code_hist.code
     *
     * @param code the value for t_code_hist.code
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }
}