package com.contest.model;

public class ProblemCasesModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_cases.id
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_cases.fid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_cases.id
     *
     * @return the value of t_problem_cases.id
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_cases.id
     *
     * @param id the value for t_problem_cases.id
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_cases.fid
     *
     * @return the value of t_problem_cases.fid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_cases.fid
     *
     * @param fid the value for t_problem_cases.fid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}