package com.contest.model;

public class ProblemCodeRestrictModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_code_restrict.id
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_code_restrict.has_prefix
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    private Boolean hasPrefix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_code_restrict.has_suffix
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    private Boolean hasSuffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_code_restrict.fid
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_code_restrict.id
     *
     * @return the value of t_problem_code_restrict.id
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_code_restrict.id
     *
     * @param id the value for t_problem_code_restrict.id
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_code_restrict.has_prefix
     *
     * @return the value of t_problem_code_restrict.has_prefix
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public Boolean getHasPrefix() {
        return hasPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_code_restrict.has_prefix
     *
     * @param hasPrefix the value for t_problem_code_restrict.has_prefix
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public void setHasPrefix(Boolean hasPrefix) {
        this.hasPrefix = hasPrefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_code_restrict.has_suffix
     *
     * @return the value of t_problem_code_restrict.has_suffix
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public Boolean getHasSuffix() {
        return hasSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_code_restrict.has_suffix
     *
     * @param hasSuffix the value for t_problem_code_restrict.has_suffix
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public void setHasSuffix(Boolean hasSuffix) {
        this.hasSuffix = hasSuffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_code_restrict.fid
     *
     * @return the value of t_problem_code_restrict.fid
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_code_restrict.fid
     *
     * @param fid the value for t_problem_code_restrict.fid
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}