package com.contest.model;

public class ProblemCasesModelWithBLOBs extends ProblemCasesModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_cases.input
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    private String input;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problem_cases.output
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    private String output;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_cases.input
     *
     * @return the value of t_problem_cases.input
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public String getInput() {
        return input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_cases.input
     *
     * @param input the value for t_problem_cases.input
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public void setInput(String input) {
        this.input = input == null ? null : input.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problem_cases.output
     *
     * @return the value of t_problem_cases.output
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problem_cases.output
     *
     * @param output the value for t_problem_cases.output
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public void setOutput(String output) {
        this.output = output == null ? null : output.trim();
    }
}