package com.contest.model;

public class RunCodeCaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_run_code_case_hist.id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_run_code_case_hist.case_id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    private Integer caseId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_run_code_case_hist.result
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_run_code_case_hist.code_id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    private Integer codeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_run_code_case_hist.id
     *
     * @return the value of t_run_code_case_hist.id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_run_code_case_hist.id
     *
     * @param id the value for t_run_code_case_hist.id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_run_code_case_hist.case_id
     *
     * @return the value of t_run_code_case_hist.case_id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public Integer getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_run_code_case_hist.case_id
     *
     * @param caseId the value for t_run_code_case_hist.case_id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public void setCaseId(Integer caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_run_code_case_hist.result
     *
     * @return the value of t_run_code_case_hist.result
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_run_code_case_hist.result
     *
     * @param result the value for t_run_code_case_hist.result
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_run_code_case_hist.code_id
     *
     * @return the value of t_run_code_case_hist.code_id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public Integer getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_run_code_case_hist.code_id
     *
     * @param codeId the value for t_run_code_case_hist.code_id
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    public void setCodeId(Integer codeId) {
        this.codeId = codeId;
    }
}