package com.contest.model;

public class UserRoleModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.id
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.uid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.rid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    private Integer rid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.id
     *
     * @return the value of t_user_role.id
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.id
     *
     * @param id the value for t_user_role.id
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.uid
     *
     * @return the value of t_user_role.uid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.uid
     *
     * @param uid the value for t_user_role.uid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.rid
     *
     * @return the value of t_user_role.rid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.rid
     *
     * @param rid the value for t_user_role.rid
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }
}