package com.contest.mapper;

import com.contest.model.CourseVideoModel;
import com.contest.model.CourseVideoModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseVideoModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    long countByExample(CourseVideoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int deleteByExample(CourseVideoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int insert(CourseVideoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int insertSelective(CourseVideoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    List<CourseVideoModel> selectByExample(CourseVideoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    CourseVideoModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseVideoModel record, @Param("example") CourseVideoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByExample(@Param("record") CourseVideoModel record, @Param("example") CourseVideoModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByPrimaryKeySelective(CourseVideoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course_video
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByPrimaryKey(CourseVideoModel record);
}