package com.contest.mapper;

import com.contest.model.CourseModel;
import com.contest.model.CourseModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CourseModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    long countByExample(CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int deleteByExample(CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int insert(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int insertSelective(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    List<CourseModel> selectByExample(CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    CourseModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") CourseModel record, @Param("example") CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByExample(@Param("record") CourseModel record, @Param("example") CourseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByPrimaryKeySelective(CourseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_course
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    int updateByPrimaryKey(CourseModel record);
}