package com.contest.mapper;

import com.contest.model.ProblemCasesModel;
import com.contest.model.ProblemCasesModelExample;
import com.contest.model.ProblemCasesModelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProblemCasesModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    long countByExample(ProblemCasesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int deleteByExample(ProblemCasesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int insert(ProblemCasesModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int insertSelective(ProblemCasesModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    List<ProblemCasesModelWithBLOBs> selectByExampleWithBLOBs(ProblemCasesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    List<ProblemCasesModel> selectByExample(ProblemCasesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    ProblemCasesModelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProblemCasesModelWithBLOBs record, @Param("example") ProblemCasesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ProblemCasesModelWithBLOBs record, @Param("example") ProblemCasesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int updateByExample(@Param("record") ProblemCasesModel record, @Param("example") ProblemCasesModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int updateByPrimaryKeySelective(ProblemCasesModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ProblemCasesModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_cases
     *
     * @mbg.generated Mon Mar 25 08:13:49 CST 2019
     */
    int updateByPrimaryKey(ProblemCasesModel record);
}