package com.contest.mapper;

import com.contest.model.ProblemDifficultyModel;
import com.contest.model.ProblemDifficultyModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProblemDifficultyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    long countByExample(ProblemDifficultyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int deleteByExample(ProblemDifficultyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int insert(ProblemDifficultyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int insertSelective(ProblemDifficultyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    List<ProblemDifficultyModel> selectByExample(ProblemDifficultyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    ProblemDifficultyModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProblemDifficultyModel record, @Param("example") ProblemDifficultyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int updateByExample(@Param("record") ProblemDifficultyModel record, @Param("example") ProblemDifficultyModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int updateByPrimaryKeySelective(ProblemDifficultyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problem_difficulty
     *
     * @mbg.generated Fri Mar 29 13:29:55 CST 2019
     */
    int updateByPrimaryKey(ProblemDifficultyModel record);
}