package com.contest.mapper;

import com.contest.model.ProblemModel;
import com.contest.model.ProblemModelExample;
import com.contest.model.ProblemModelWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProblemModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    long countByExample(ProblemModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int deleteByExample(ProblemModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int insert(ProblemModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int insertSelective(ProblemModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    List<ProblemModelWithBLOBs> selectByExampleWithBLOBs(ProblemModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    List<ProblemModel> selectByExample(ProblemModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    ProblemModelWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProblemModelWithBLOBs record, @Param("example") ProblemModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ProblemModelWithBLOBs record, @Param("example") ProblemModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByExample(@Param("record") ProblemModel record, @Param("example") ProblemModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByPrimaryKeySelective(ProblemModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ProblemModelWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_problems
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByPrimaryKey(ProblemModel record);
}