package com.contest.mapper;

import com.contest.model.RunCodeCaseModel;
import com.contest.model.RunCodeCaseModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RunCodeCaseModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    long countByExample(RunCodeCaseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int deleteByExample(RunCodeCaseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int insert(RunCodeCaseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int insertSelective(RunCodeCaseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    List<RunCodeCaseModel> selectByExample(RunCodeCaseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    RunCodeCaseModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") RunCodeCaseModel record, @Param("example") RunCodeCaseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int updateByExample(@Param("record") RunCodeCaseModel record, @Param("example") RunCodeCaseModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int updateByPrimaryKeySelective(RunCodeCaseModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_run_code_case_hist
     *
     * @mbg.generated Thu Apr 04 10:27:28 CST 2019
     */
    int updateByPrimaryKey(RunCodeCaseModel record);
}