package com.contest.mapper;

import com.contest.model.UserProblemSolveStateModel;
import com.contest.model.UserProblemSolveStateModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserProblemSolveStateModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    long countByExample(UserProblemSolveStateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int deleteByExample(UserProblemSolveStateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int insert(UserProblemSolveStateModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int insertSelective(UserProblemSolveStateModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    List<UserProblemSolveStateModel> selectByExample(UserProblemSolveStateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    UserProblemSolveStateModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserProblemSolveStateModel record, @Param("example") UserProblemSolveStateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByExample(@Param("record") UserProblemSolveStateModel record, @Param("example") UserProblemSolveStateModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByPrimaryKeySelective(UserProblemSolveStateModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_problem_solve_state
     *
     * @mbg.generated Thu Jun 20 13:21:50 CST 2019
     */
    int updateByPrimaryKey(UserProblemSolveStateModel record);
}