package com.contest.model;

public class CourseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.id
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.name
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.pic
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.status
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.isCharge
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    private String ischarge;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.learned_num
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    private Integer learnedNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course.comment_num
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    private Integer commentNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.id
     *
     * @return the value of t_course.id
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.id
     *
     * @param id the value for t_course.id
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.name
     *
     * @return the value of t_course.name
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.name
     *
     * @param name the value for t_course.name
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.pic
     *
     * @return the value of t_course.pic
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.pic
     *
     * @param pic the value for t_course.pic
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.status
     *
     * @return the value of t_course.status
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.status
     *
     * @param status the value for t_course.status
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.isCharge
     *
     * @return the value of t_course.isCharge
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public String getIscharge() {
        return ischarge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.isCharge
     *
     * @param ischarge the value for t_course.isCharge
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public void setIscharge(String ischarge) {
        this.ischarge = ischarge == null ? null : ischarge.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.learned_num
     *
     * @return the value of t_course.learned_num
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public Integer getLearnedNum() {
        return learnedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.learned_num
     *
     * @param learnedNum the value for t_course.learned_num
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public void setLearnedNum(Integer learnedNum) {
        this.learnedNum = learnedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course.comment_num
     *
     * @return the value of t_course.comment_num
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course.comment_num
     *
     * @param commentNum the value for t_course.comment_num
     *
     * @mbg.generated Wed May 08 11:00:42 CST 2019
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

	@Override
	public String toString() {
		return "CourseModel [id=" + id + ", name=" + name + ", pic=" + pic + ", status=" + status + ", ischarge="
				+ ischarge + ", learnedNum=" + learnedNum + ", commentNum=" + commentNum + "]";
	}
    
    
}