package com.contest.model;

public class CourseVideoModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_video.id
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_video.name
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_video.serial
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private Integer serial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_video.fid
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private Integer fid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_video.id
     *
     * @return the value of t_course_video.id
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_video.id
     *
     * @param id the value for t_course_video.id
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_video.name
     *
     * @return the value of t_course_video.name
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_video.name
     *
     * @param name the value for t_course_video.name
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_video.serial
     *
     * @return the value of t_course_video.serial
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public Integer getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_video.serial
     *
     * @param serial the value for t_course_video.serial
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setSerial(Integer serial) {
        this.serial = serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_video.fid
     *
     * @return the value of t_course_video.fid
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_video.fid
     *
     * @param fid the value for t_course_video.fid
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }
}