package com.contest.model;

public class CourseInforModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_infor.id
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_infor.infor_pic
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private String inforPic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_infor.fid
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private Integer fid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_course_infor.infor
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    private String infor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_infor.id
     *
     * @return the value of t_course_infor.id
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_infor.id
     *
     * @param id the value for t_course_infor.id
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_infor.infor_pic
     *
     * @return the value of t_course_infor.infor_pic
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public String getInforPic() {
        return inforPic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_infor.infor_pic
     *
     * @param inforPic the value for t_course_infor.infor_pic
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setInforPic(String inforPic) {
        this.inforPic = inforPic == null ? null : inforPic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_infor.fid
     *
     * @return the value of t_course_infor.fid
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_infor.fid
     *
     * @param fid the value for t_course_infor.fid
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_course_infor.infor
     *
     * @return the value of t_course_infor.infor
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public String getInfor() {
        return infor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_course_infor.infor
     *
     * @param infor the value for t_course_infor.infor
     *
     * @mbg.generated Thu Jun 20 13:21:51 CST 2019
     */
    public void setInfor(String infor) {
        this.infor = infor == null ? null : infor.trim();
    }
}