package com.contest.model;

public class ProblemModelWithBLOBs extends ProblemModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problems.description
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problems.input
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    private String input;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_problems.output
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    private String output;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problems.description
     *
     * @return the value of t_problems.description
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problems.description
     *
     * @param description the value for t_problems.description
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problems.input
     *
     * @return the value of t_problems.input
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    public String getInput() {
        return input;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problems.input
     *
     * @param input the value for t_problems.input
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    public void setInput(String input) {
        this.input = input == null ? null : input.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_problems.output
     *
     * @return the value of t_problems.output
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    public String getOutput() {
        return output;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_problems.output
     *
     * @param output the value for t_problems.output
     *
     * @mbg.generated Sat Mar 02 20:35:19 CST 2019
     */
    public void setOutput(String output) {
        this.output = output == null ? null : output.trim();
    }
}